dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8

before_script:
  - mkdir build
  - cd build

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 cmake ..
  - cmake --build . -- -j2
  - ./rationals/rationals
  - ./matrix/matrix

